// <auto-generated />
using DogOffices.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogOffices.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181117173941_AddDogsAndChangedCompanyPropNames")]
    partial class AddDogsAndChangedCompanyPropNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogOffices.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAddress");

                    b.Property<string>("CompanyCity");

                    b.Property<string>("CompanyDescription");

                    b.Property<int>("CompanyDogId");

                    b.Property<string>("CompanyName");

                    b.Property<string>("CompanyState");

                    b.Property<string>("CompanyWebsiteUrl");

                    b.Property<int>("CompanyZipCode");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new { CompanyId = 1, CompanyAddress = "1234 Main Street", CompanyCity = "Willoughby", CompanyDescription = "Viva Spanish provides Spanish language programs for non-public K-8 Ohio Schools. Super dog friendly. At any give time there may be 4 dogs in the office.", CompanyDogId = 0, CompanyName = "Viva Spanish", CompanyState = "Ohio", CompanyWebsiteUrl = "www.vivaspanish.com", CompanyZipCode = 44094 }
                    );
                });

            modelBuilder.Entity("DogOffices.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<string>("DogBreed");

                    b.Property<string>("DogDescription");

                    b.Property<string>("DogName");

                    b.HasKey("DogId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("DogOffices.Models.Dog", b =>
                {
                    b.HasOne("DogOffices.Models.Company")
                        .WithMany("CompanyDogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
